name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    name: generate-github-metrics
    permissions:
      contents: write

    steps:
      # Classic metrics
      - name: Classic metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: HongKong
          output_action: commit
          output_path: metrics
          filename: metrics.svg
          committer_branch: main
          committer_message: "📊 Update GitHub metrics"

      # Full-year isocalendar
      - name: Full year isocalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: HongKong
          output_action: commit
          output_path: metrics
          filename: fullyear.svg
          committer_branch: main
          committer_message: "📊 Update GitHub metrics"

      # Stargazers worldmap
      - name: Stargazers worldmap
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200
          output_action: commit
          output_path: metrics
          filename: stargazersworldmap.svg
          committer_branch: main
          committer_message: "📊 Update GitHub metrics"

      # Compact achievements
      - name: Compact achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          output_action: commit
          output_path: metrics
          filename: achievementscompact.svg
          committer_branch: main
          committer_message: "📊 Update GitHub metrics"

