name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 1 * * 1,4"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    name: generate-github-metrics
    permissions:
      contents: write

    steps:
      # Checkout repository first with authentication
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PROFILE }}

      # Create both directories
      - name: Create directories
        run: |
          #mkdir -p ${{ github.workspace }}/metrics_renders
          mkdir -p ${{ github.workspace }}/metrics
      # Generate metrics (disable auto-commit)
      - name: Classic metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: HongKong
          output_action: none  # Disable auto-commit
          #output_path: ${{ github.workspace }}/metrics_renders/
          filename: metrics.svg

      - name: Full year isocalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: HongKong
          output_action: none
          #output_path: ${{ github.workspace }}/metrics_renders/
          filename: fullyear.svg

      - name: Compact achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PROFILE }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: "X"
          output_action: none
          #output_path: ${{ github.workspace }}/metrics_renders/
          filename: achievementscompact.svg

      # Copy and commit all files
      - name: Process and commit metrics
        run: |
          echo "=== Before copy ==="
          echo "Metrics_renders contents:"
          ls -la /metrics_renders/
          
          # Copy files
          #cp ${{ github.workspace }}/metrics_renders/*.svg ${{ github.workspace }}/metrics/
          cp /metrics_renders/*.svg ${{ github.workspace }}/metrics/
          
          echo "=== After copy ==="
          echo "Metrics contents:"
          ls -la ${{ github.workspace }}/metrics/
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ github.workspace }}/metrics/
          git commit -m "📊 Update GitHub metrics"
          git push
