name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    name: generate-github-metrics
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Lisbon

          # Plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_stargazers: yes
          plugin_followup: yes
          plugin_traffic: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_isocalendar: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_notable: yes

          filename: metrics.svg
          committer_branch: gh-pages
          committer_message: "📊 Update GitHub metrics"
